config/routes.rb
Resignako::Application.routes.draw do
  
  get "fb_oauth/start"

  get "fb_oauth/callback"

  
  
  match 'admin_actions/manage_spam/:id/:task' => 'admin_actions#manage_spam', as: 'manage_spam'
  match 'admin_actions/manage_posts/:id/:task' => 'admin_actions#manage_posts', as: 'manage_posts'
  
  match 'admin_actions/edit_seed/:id' => 'admin_actions#edit_seed', as: 'edit_seed', via: [:get, :put]
  match 'admin_actions/force_push/:id' => 'admin_actions#force_push', as: 'force_push', via: [:post]
  match 'admin_actions/delete_queue/:id' => 'admin_actions#delete_queue', as: 'delete_queue', via: [:delete]
  match 'admin_actions/upload_advert/:id' => 'admin_actions#upload_advert', as: 'upload_advert', via: [:post, :get]
  match 'free/:hash' => 'posts#single', :as => :single
  
  match "admin_actions"   => 'admin_actions#index'
  
  get "admin_actions/manage_adverts"
  get "admin_actions/manage_queue"
  get "admin_actions/manage_spam"
  get "admin_actions/manage_posts"  
  get "admin_actions/add_seed"
  post "admin_actions/create_seed"
  post "admin_actions/consume_queue"
  get "admin_actions/consume_queue"
  
  get "admins/login"
  resources :admins
  
  resources :admin_sessions, only: [:new, :create, :destroy]
  match '/signin', to: 'admin_sessions#new'
  match '/signout', to: 'admin_sessions#destroy', via: :delete
  
  match '/change_password', to: 'admin_sessions#change_password', via: [:get, :post]
  match '/change_pw', to: 'admin_sessions#admin_change_password', via: [:get, :put]
  
  get "contact_form/new"
  get "contact_form/create"
  get "company/about"
  get "company/contact"
  get "company/terms"

  get "users/add"
  get "users/edit"
  get "users/delete"

  get "posts/hot"
  get "posts/new"
  get "posts/submit"
  get "posts/vote_down"
  get "posts/report"
  get "posts/single"
  post "posts/create"
  get "posts/verify"
  
  match "posts/vote_up/:id", to: 'posts#vote_up', as: 'post_vote_up'
  match "posts/vote_down/:id", to: 'posts#vote_down', as: 'post_vote_down'
  match "posts/update_vote_up/:id", to: 'posts#update_vote_up', as: 'post_update_vote_up'
  match "posts/update_vote_down/:id", to: 'posts#update_vote_down', as: 'post_update_vote_down'
  match "posts/report/:id", to: 'posts#report', as: 'post_report'
  
  match 'about' => 'company#about'
  match 'terms' => 'company#terms'
  match 'topgood' => 'posts#top_good'
  match 'topbad' => 'posts#top_bad'
  match 'new' => 'posts#new'
  match 'hot' => 'posts#hot'
  match 'submit' => 'posts#submit'
  match 'contact' => 'contact_form#new'
  
  match 'feed' => 'posts#feed'
  
  match 'register' => 'users#register'
  
  get 'posts/fb_verify'
  get 'posts/callback'
  
  post "contact_form/create"
  

  
  root :to => 'posts#new'

end

app/views/admins/add.html.erb
<h1>Admins#add</h1>
<p>Find me in app/views/admins/add.html.erb</p>

app/views/admins/add_seed.html.erb
<div id="admin-add-seed-page">
<h3>Add Seed Content</h3>
<%= form_for :post, url: create_seed_url do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  
  <%= f.label :name %>
  <%= f.number_field :name %>
  
  <%= f.label :age %>
  <%= f.number_field :age %>
  
  <%= f.label :former_job %>
  <%= f.text_field :former_job %>
  
  <%= f.submit "Add Content" %>
<% end %>
</div>

app/views/admins/change_password.html.erb
<h1>Admins#change_password</h1>
<p>Find me in app/views/admins/change_password.html.erb</p>

app/views/admins/edit.html.erb
<div id="admins-show">
<%#form type="POST" action="<%= edit_admin_path(@admin) " class="form-horizontal"> %>
  <h3>Edit Basic Information</h3>
      <%= render 'shared/admin_error_messages' %>

  <%= form_for @admin, :html => { class: "form-horizontal" } do |f| %>
    <div class="control-group">
      <%= f.label :name, class: "control-label" %>
      <div class="controls"><%= f.text_field :name %></div>
    </div>
    <div class="control-group">
      <%= f.label :email, class: "control-label" %>
      <div class="controls"><%= f.text_field :email %></div>
    </div>
    <div class="control-group">
      <div class="control-label"></div>
      <%= f.submit "Update Admin", class: "btn btn-small btn-primary" %>
       <div class="clear"></div>
    </div>
  <% end %>
  
  <h3>Edit Password</h3>
      <%= render 'shared/admin_error_messages' %>

  <%= form_for @admin, :html => { class: "form-horizontal" } do |f| %>
    	<%= f.hidden_field :name %>
      <%= f.hidden_field :email %>
    <div class="control-group">
      <%= f.label :password, class: "control-label" %>
      <div class="controls"><%= f.password_field :password %></div>
    </div>
    <div class="control-group">
      <%= f.label :password_confirmation, class: "control-label" %>
      <div class="controls"><%= f.password_field :password_confirmation %></div>
    </div>
    <div class="control-group">
      <div class="control-label"></div>
      <%= f.submit "Update Admin", class: "btn btn-small btn-primary" %>
       <div class="clear"></div>
    </div>
  <% end %>
  <%#/form> %>
</div>

app/views/admins/index.html.erb
<div class="admin-action-pages">
<h1>Admin List</h1>
<table class="table table-striped">
  <tr><th>ID</th><th>Name</th><th>Email</th><th>Role</th><th>Action</th></tr>
  <% @admins.each do |admin| %>
  <tr>
    <td><%= admin.id %></td>
    <td><%= admin.name %></td>
    <td><%= admin.email %></td>
    <td><%= admin.role %></td>
    <td>
      <%= link_to "Edit", edit_admin_path(admin) %> |
      <%= link_to "Delete", admin_path(admin), method: "delete" %>
    </td>
  </tr>
  <% end %>
</table>
<%= paginate @admins %>
</div>

app/views/admins/login.html.erb
<%= form_for :admin do |f|%>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.label :password%>
  <%= f.password_field :password %>
  <div class="clear"></div>
  <%= f.submit "Login", class: "btn btn-primary"%>
<% end %>

app/views/admins/manage_posts.html.erb
<h1>Admins#manage_posts</h1>
<p>Find me in app/views/admins/manage_posts.html.erb</p>

app/views/admins/new.html.erb
<div id="admins-new">
  <h2>Add New Admin</h2>
<%#form type="POST" action="<%= edit_admin_path(@admin) " class="form-horizontal"> %>
  <%= form_for @admin do |f| %>
      <%= render 'shared/admin_error_messages' %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>
     
      <div class="clear"></div>
      <%= f.submit "Add New Admin", class: "btn btn-large btn-primary" %>
  <% end %>
  <%#/form> %>
</div>

app/views/admins/show.html.erb
<div id="admins-show">
  <h2><%= @admin.name %></h2>
<%#form type="POST" action="<%= edit_admin_path(@admin) " class="form-horizontal"> %>
  <h3><%= @admin.email%></h3>
  <div><%= link_to "Edit", edit_admin_path(@admin) %></div>
</div>

app/views/admins/spam.html.erb
<h1>Admins#spam</h1>
<p>Find me in app/views/admins/spam.html.erb</p>