config/routes.rb
Resignako::Application.routes.draw do
  
  get "fb_oauth/start"

  get "fb_oauth/callback"

  
  
  match 'admin_actions/manage_spam/:id/:task' => 'admin_actions#manage_spam', as: 'manage_spam'
  match 'admin_actions/manage_posts/:id/:task' => 'admin_actions#manage_posts', as: 'manage_posts'
  
  match 'admin_actions/edit_seed/:id' => 'admin_actions#edit_seed', as: 'edit_seed', via: [:get, :put]
  match 'admin_actions/force_push/:id' => 'admin_actions#force_push', as: 'force_push', via: [:post]
  match 'admin_actions/delete_queue/:id' => 'admin_actions#delete_queue', as: 'delete_queue', via: [:delete]
  match 'admin_actions/upload_advert/:id' => 'admin_actions#upload_advert', as: 'upload_advert', via: [:post, :get]
  match 'free/:hash' => 'posts#single', :as => :single
  
  match "admin_actions"   => 'admin_actions#index'
  
  get "admin_actions/manage_adverts"
  get "admin_actions/manage_queue"
  get "admin_actions/manage_spam"
  get "admin_actions/manage_posts"  
  get "admin_actions/add_seed"
  post "admin_actions/create_seed"
  post "admin_actions/consume_queue"
  get "admin_actions/consume_queue"
  
  get "admins/login"
  resources :admins
  
  resources :admin_sessions, only: [:new, :create, :destroy]
  match '/signin', to: 'admin_sessions#new'
  match '/signout', to: 'admin_sessions#destroy', via: :delete
  
  match '/change_password', to: 'admin_sessions#change_password', via: [:get, :post]
  match '/change_pw', to: 'admin_sessions#admin_change_password', via: [:get, :put]
  
  get "contact_form/new"
  get "contact_form/create"
  get "company/about"
  get "company/contact"
  get "company/terms"

  get "users/add"
  get "users/edit"
  get "users/delete"

  get "posts/hot"
  get "posts/new"
  get "posts/submit"
  get "posts/vote_down"
  get "posts/report"
  get "posts/single"
  post "posts/create"
  get "posts/verify"
  
  match "posts/vote_up/:id", to: 'posts#vote_up', as: 'post_vote_up'
  match "posts/vote_down/:id", to: 'posts#vote_down', as: 'post_vote_down'
  match "posts/update_vote_up/:id", to: 'posts#update_vote_up', as: 'post_update_vote_up'
  match "posts/update_vote_down/:id", to: 'posts#update_vote_down', as: 'post_update_vote_down'
  match "posts/report/:id", to: 'posts#report', as: 'post_report'
  
  match 'about' => 'company#about'
  match 'terms' => 'company#terms'
  match 'topgood' => 'posts#top_good'
  match 'topbad' => 'posts#top_bad'
  match 'new' => 'posts#new'
  match 'hot' => 'posts#hot'
  match 'submit' => 'posts#submit'
  match 'contact' => 'contact_form#new'
  
  match 'feed' => 'posts#feed'
  
  match 'register' => 'users#register'
  
  get 'posts/fb_verify'
  get 'posts/callback'
  
  post "contact_form/create"
  

  
  root :to => 'posts#new'

end

app/controllers/admin_sessions_controller.rb
class AdminSessionsController < ApplicationController
  layout "blank_base"
  
  def new
  end
  
  def create
    
    @admin = Admin.find_by_email(params[:session][:email])
    if @admin && @admin.authenticate(params[:session][:password])
      sign_in @admin
      redirect_to admins_path
    else 
      flash.now[:error] = 'Invalid email/password combination'
      render "new"
    end
  end
  
  def destroy
    sign_out
    redirect_to root_url
  end
  
  def change_password
    if request.post?
      @admin = Admin.find_by_email(params[:session][:email])
      if @admin
        _link = change_pw_url({ email: @admin.email, secret: Digest::MD5.hexdigest(@admin.updated_at.to_s) })
        AdminPasswordMailer.email_password(@admin, _link).deliver
        flash.now[:success] = 'Reset Email request has been sent!'
      else 
        flash.now[:error] = 'Email does not exist in our records.'
      end
      render 'change_password'
    end
  end
  
  def admin_change_password 
    if request.put?
      @admin = Admin.find_by_email(params[:admin][:email])
      if @admin
        if( @admin.update_attributes(params[:admin]) ) 
          redirect_to '/signin'
        else
          flash.now[:error] = "Password Error. Please Try again"
          render 'admin_change_password'
        end
      end
    else 
      @admin = Admin.find_by_email(params[:email])
      secret = params[:secret]
      
      if secret != Digest::MD5.hexdigest(@admin.updated_at.to_s)
        flash.now[:error] = "Sorry, the link that you are using has expired. Please request another reset."
        render 'change_password'
      end
    end
  end
end

app/helpers/admin_sessions_helper.rb
module AdminSessionsHelper

  def sign_in(admin)
    cookies.permanent[:remember_token] = { value:   admin.remember_token,
                                           expires: 20.years.from_now.utc }
    self.current_admin = admin
  end

  def sign_out
    self.current_admin = nil
    cookies.delete(:remember_token)
  end
  
  def current_admin=(admin)
    current_admin = admin
  end
  
  def current_admin
    current_admin ||= Admin.find_by_remember_token(cookies[:remember_token])
  end
  
  def admin_signedin?
    !current_admin.nil?
  end

end

app/views/admin_sessions/admin_change_password.html.erb
<div id="admin-sessions-new-page" class="admin-sessions-area">
<div class="center hero-unit">
  <h1>NagResignAko Admin Pages</h1>  
</div>
<div class="form-area">
  <h4>Set Password</h4>
  <h5>Please reset your password.</h5>
  <%= form_for @admin, url: change_pw_path do |f|%>
    <%= render 'shared/admin_error_messages' %>
    <%= f.hidden_field :email %>
    <%= f.hidden_field :name %>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
    <div class="clear"></div>
    <%= f.submit "Login", class: "btn btn-primary pull-right"%>
  <% end %>
</div>
</div>

app/views/admin_sessions/change_password.html.erb
<div id="admin-sessions-new-page" class="admin-sessions-area">
<div class="center hero-unit">
  <h1>NagResignAko Admin Pages</h1>  
</div>
<div class="form-area">
  <h4>Forgot Password</h4>
  <h5>Please input your email. We will then send you a new password request link.</h5>
  <%= form_for :session, url: change_password_url, class: "form-horizontal" do |f|%>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <div class="clear"></div>
    <%= f.submit "Login", class: "btn btn-primary pull-right"%>
  <% end %>
</div>
</div>

app/views/admin_sessions/new.html.erb
<div id="admin-sessions-new-page" class="admin-sessions-area">
<div class="center hero-unit">
  <h1>NagResignAko Admin Pages</h1>  
</div>
<div class="form-area">
  <%= form_for :session, url: admin_sessions_path, class: "form-horizontal" do |f|%>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <%= f.label :password%>
    <%= f.password_field :password %>
    <div class="clear"></div>
    <%= link_to "Forgot Password?", change_password_path %>
    <%= f.submit "Login", class: "btn btn-primary pull-right"%>
  <% end %>
</div>
</div>