config/routes.rb
Resignako::Application.routes.draw do
  
  get "fb_oauth/start"

  get "fb_oauth/callback"

  
  
  match 'admin_actions/manage_spam/:id/:task' => 'admin_actions#manage_spam', as: 'manage_spam'
  match 'admin_actions/manage_posts/:id/:task' => 'admin_actions#manage_posts', as: 'manage_posts'
  
  match 'admin_actions/edit_seed/:id' => 'admin_actions#edit_seed', as: 'edit_seed', via: [:get, :put]
  match 'admin_actions/force_push/:id' => 'admin_actions#force_push', as: 'force_push', via: [:post]
  match 'admin_actions/delete_queue/:id' => 'admin_actions#delete_queue', as: 'delete_queue', via: [:delete]
  match 'admin_actions/upload_advert/:id' => 'admin_actions#upload_advert', as: 'upload_advert', via: [:post, :get]
  match 'free/:hash' => 'posts#single', :as => :single
  
  match "admin_actions"   => 'admin_actions#index'
  
  get "admin_actions/manage_adverts"
  get "admin_actions/manage_queue"
  get "admin_actions/manage_spam"
  get "admin_actions/manage_posts"  
  get "admin_actions/add_seed"
  post "admin_actions/create_seed"
  post "admin_actions/consume_queue"
  get "admin_actions/consume_queue"
  
  get "admins/login"
  resources :admins
  
  resources :admin_sessions, only: [:new, :create, :destroy]
  match '/signin', to: 'admin_sessions#new'
  match '/signout', to: 'admin_sessions#destroy', via: :delete
  
  match '/change_password', to: 'admin_sessions#change_password', via: [:get, :post]
  match '/change_pw', to: 'admin_sessions#admin_change_password', via: [:get, :put]
  
  get "contact_form/new"
  get "contact_form/create"
  get "company/about"
  get "company/contact"
  get "company/terms"

  get "users/add"
  get "users/edit"
  get "users/delete"

  get "posts/hot"
  get "posts/new"
  get "posts/submit"
  get "posts/vote_down"
  get "posts/report"
  get "posts/single"
  post "posts/create"
  get "posts/verify"
  
  match "posts/vote_up/:id", to: 'posts#vote_up', as: 'post_vote_up'
  match "posts/vote_down/:id", to: 'posts#vote_down', as: 'post_vote_down'
  match "posts/update_vote_up/:id", to: 'posts#update_vote_up', as: 'post_update_vote_up'
  match "posts/update_vote_down/:id", to: 'posts#update_vote_down', as: 'post_update_vote_down'
  match "posts/report/:id", to: 'posts#report', as: 'post_report'
  
  match 'about' => 'company#about'
  match 'terms' => 'company#terms'
  match 'topgood' => 'posts#top_good'
  match 'topbad' => 'posts#top_bad'
  match 'new' => 'posts#new'
  match 'hot' => 'posts#hot'
  match 'submit' => 'posts#submit'
  match 'contact' => 'contact_form#new'
  
  match 'feed' => 'posts#feed'
  
  match 'register' => 'users#register'
  
  get 'posts/fb_verify'
  get 'posts/callback'
  
  post "contact_form/create"
  

  
  root :to => 'posts#new'

end

app/controllers/admin_actions_controller.rb
class AdminActionsController < ApplicationController
  layout "admin_base"
  before_filter :redirect_if_loggedout  

  def index
    redirect_to '/admins'
  end
  
  def add_seed
    @post = Post.new
  end
  
  def edit_seed
    if request.get?
      @post = Post.find(params[:id])
    elsif request.put?
      @post = Post.find(params[:id]) 
      @post.name = params[:post][:name]
      @post.age = params[:post][:age]
      @post.entry = params[:post][:entry]
      @post.former_job = params[:post][:former_job]
      
      if (@post.save)
        redirect_to admin_actions_manage_posts_path, flash: { success: "Seed content successfully edited!" }
      end
    end  
  end 
  def create_seed
    
      @user = User.find_by_email (current_admin.email)
    
      if (@user == nil) 
        @user = User.create({ email: current_admin.email })
      end
    
    @post = Post.new(params[:post]);
    @post.user_id = @user.id
    @post.verified = TRUE
    @post.permalink = Digest::MD5.hexdigest(@user.email + '' + Date.today.to_formatted_s(:db))
    @post.save

    redirect_to request.referer, flash: { success: "Seed content successfully added!" }
  end

  def manage_posts
    #TODO: PAGINATE THIS BITCH
    id ||= params[:id]
    action  ||= params[:task]
    params[:page] = params[:page] ? params[:page] : 0
    
    if request.get?
      @posts = Post.order("id desc").page(params[:page]).per(5)
      #where reported_spam < 10
    elsif request.post?
      _post = Post.find(id)
      
      if _post == nil
        redirect_to admin_actions_manage_posts_path
      end
      
      if (action == "hide")
        _post.reported_spam += 10
        _post.save
        
        redirect_to request.referer, flash: { success: "Post id #{_post.id} has been marked as spam." }
      elsif (action == "queue")
       
        _post.queued = TRUE
        _post.save
        
        PostQueue.create(post: _post, pushed: FALSE)
        redirect_to request.referer, flash: {success: "Post ID #{_post.id} has been added to the Social Push Queue."}
      elsif (action == "unqueue")
        _post.queued = FALSE
        _post.save
        
        _post.post_queue.destroy
        redirect_to request.referer, flash: {success: "Post ID #{_post.id} has been removed from the Social Push Queue."}
      end
      
    elsif request.delete?
      _post = Post.find(id) #catch null
      
      if _post == nil
        redirect_to admin_actions_manage_posts_path
      end
      
      _post.destroy
      
      redirect_to request.referer, flash: { success: "Post id #{_post.id} has been deleted." } 
    end
  end

  def manage_spam
    task = params[:task] || nil
    params[:page] = params[:page] ? params[:page] : 0
    
    if request.get?
      @posts =     Post.where("reported_spam > 0").order("id desc").page(params[:page]).per(5)
    elsif request.post? && task=="show" #post is not a spam
      _post = Post.find(params[:id])
      _post.reported_spam = 0
      _post.save
      
      
      @posts =     Post.where("reported_spam > 0").page(params[:page]).per(5)
      
      redirect_to request.referer, flash: { success: "Successfully removed spam status of entry id #{_post.id}" }
      
    elsif request.delete? && task=="delete"
      _post = Post.find(params[:id])
      _post.destroy
      
      @posts =     Post.where("reported_spam > 0").page(params[:page]).per(5)
      redirect_to request.referer, flash: { success: "Successfully deleted spam from database"}
    end
      
  end

  def manage_queue
    #Order this by datetime

    pushed = params[:pushed] != nil && params[:pushed] == "true"
    
    #TODO make activerecord
    @queue_items = PostQueue.where((pushed ? "": "NOT ") + "pushed AND post_id IS NOT NULL").order("id desc").page(params[:page]).per(5)
    @pushed = pushed
  end
  
  def force_push
    _queue_item = PostQueue.find(params[:id])

    social_push _queue_item
    redirect_to request.referrer, flash: { success: "Post item has been pushed successfully!" }
  end
  
  def consume_queue
    #PostsHelper
    social_push  
    
    if request.get?
      render :nothing => true, :status => 200, :content_type => 'text/html'
    else
      redirect_to request.referrer, flash: { success: "Queue has been consumed!"}
    end
    
  end

  def manage_adverts
  end
  
  def upload_advert
    logger.info "Entered UPLOAD ADVERT!!"
    id ||= Integer(params[:id])
    tmp = params[:advert][:upload].tempfile
  
    filename = params[:advert][:upload].original_filename
    extension = File.extname(params[:advert][:upload].original_filename)
    
    if (! %w[.jpg .gif .png].include? extension.downcase )  
      redirect_to request.referer, flash: { error: "Invalid File Format. Only Accepts: jpg, gif, and png" }
      return
    end
    
    file = File.join("app/assets/images/adverts", id > 0 ? "scrolling-advert-#{id}#{extension}" : "sidebar-right#{extension}")
    FileUtils.cp tmp.path, file
    
    #FileUtils.rm file
    
    logger.info "LEAVING upload_adverts!!"
    
    advert = id > 0 ? "Scrolling Advert banner # #{id}" : "Sidebar Advert"
    redirect_to request.referer, flash: { success: "#{advert} Successfully Updated!"}
  end
  
end

app/helpers/admin_actions_helper.rb
module AdminActionsHelper
end

app/views/admin_actions/add.html.erb
<h1>Admins#add</h1>
<p>Find me in app/views/admins/add.html.erb</p>

app/views/admin_actions/add_seed.html.erb
<div id="admin-add-seed-page">
<%= form_for :post, url: admin_actions_create_seed_path do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>
  
  <%= f.label :name %>
  <%= f.text_field :name %>
  
  <%= f.label :age %>
  <%= f.number_field :age %>
  
  <%= f.label :former_job %>
  <%= f.text_field :former_job %>
  
  <%= f.label :entry %>
  <%= f.text_field :entry %>
  <div>
    <%= f.submit "Add Content", class: "btn btn-primary" %>
  </div>
<% end %>
</div>

app/views/admin_actions/change_password.html.erb
<h1>Admins#change_password</h1>
<p>Find me in app/views/admins/change_password.html.erb</p>

app/views/admin_actions/edit.html.erb
<div id="admins-show">
<%#form type="POST" action="<%= edit_admin_path(@admin) " class="form-horizontal"> %>
  <h3>Edit Basic Information</h3>
      <%= render 'shared/admin_error_messages' %>

  <%= form_for @admin, :url => admin_action_path, :html => { class: "form-horizontal" } do |f| %>
    <div class="control-group">
      <%= f.label :name, class: "control-label" %>
      <div class="controls"><%= f.text_field :name %></div>
    </div>
    <div class="control-group">
      <%= f.label :email, class: "control-label" %>
      <div class="controls"><%= f.text_field :email %></div>
    </div>
    <div class="control-group">
      <div class="control-label"></div>
      <%= f.submit "Update Admin", class: "btn btn-small btn-primary" %>
       <div class="clear"></div>
    </div>
  <% end %>
  
  <h3>Edit Password</h3>
      <%= render 'shared/admin_error_messages' %>

  <%= form_for @admin, :url => admin_action_path, :html => { class: "form-horizontal" } do |f| %>
    	<%= f.hidden_field :name %>
      <%= f.hidden_field :email %>
    <div class="control-group">
      <%= f.label :password, class: "control-label" %>
      <div class="controls"><%= f.password_field :password %></div>
    </div>
    <div class="control-group">
      <%= f.label :password_confirmation, class: "control-label" %>
      <div class="controls"><%= f.password_field :password_confirmation %></div>
    </div>
    <div class="control-group">
      <div class="control-label"></div>
      <%= f.submit "Update Admin", class: "btn btn-small btn-primary" %>
       <div class="clear"></div>
    </div>
  <% end %>
  <%#/form> %>
</div>

app/views/admin_actions/edit_seed.html.erb
<div id="admin-add-seed-page">
<%= form_for @post, url: edit_seed_url(@post.id), :html=>{:method=>:put} do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>
  
  <%= f.label :name %>
  <%= f.text_field :name %>
  
  <%= f.label :age %>
  <%= f.number_field :age %>
  
  <%= f.label :former_job %>
  <%= f.text_field :former_job %>
  
  <%= f.label :entry %>
  <%= f.text_area :entry, cols: 40, rows: 5 %>
  <div>
    <%= f.submit "Edit Content", class: "btn btn-primary" %>
  </div>
<% end %>
</div>

app/views/admin_actions/index.html.erb
<h1>Admin List</h1>
<table class="table table-striped">
  <tr><th>ID</th><th>Name</th><th>Email</th><th>Role</th><th>Action</th></tr>
  <% @admins.each do |admin| %>
  <tr>
    <td><%= admin.id %></td>
    <td><%= admin.name %></td>
    <td><%= admin.email %></td>
    <td><%= admin.role %></td>
    <td>
      <%= link_to "Edit", edit_admin_action_path(admin) %> |
      <%= link_to "Delete", admin_action_url(admin), method: "delete" %>
    </td>
  </tr>
  <% end %>
</table>

app/views/admin_actions/login.html.erb
<%= form_for :admin do |f|%>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.label :password%>
  <%= f.password_field :password %>
  <div class="clear"></div>
  <%= f.submit "Login", class: "btn btn-primary"%>
<% end %>

app/views/admin_actions/manage_adverts.html.erb
<div id="manage-adverts-page">
  <h2>Advert Management</h2>
  <article>This area allows the user to change the adverts being shown in the site. 
      They should all redirect to a URL described by the client. For now, only developers can change the URL for
      the redirection.</article>
  <table class="table table-striped">
    <thead>
      <tr><th>Image Banner</th>
          <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <%#Main Banner%>
        <td>
          <h5>Right Sidebar Banner</h5>
          <%= image_tag load_advert "sidebar-right", "http://placehold.it/651x85" %>
        </td>
        <td><%= form_for :advert, url: upload_advert_url(0), multipart: true do |f| %>
             <%= f.label "Select File" %>
             <%= f.file_field "upload" %>

              <%= submit_tag "Upload" %>
          <% end %></td>
      </tr>
      <tr>
        <%#Rolling Banner # 1%>
        <td>
          <h5>Rolling Advert Banner # 1</h5>
          <%= image_tag load_advert "scrolling-advert-1", "http://placehold.it/651x85" %>
        </td>
        <td><%= form_for :advert, url: upload_advert_url(1), multipart: true do |f| %>
             <%= f.label "Select File" %>
             <%= f.file_field "upload" %>

              <%= submit_tag "Upload" %>
          <% end %></td>
      </tr>
      <tr>
        <td>
            <h5>Rolling Advert Banner # 2</h5>
            <%= image_tag load_advert "scrolling-advert-2", "http://placehold.it/651x85" %>
        </td>
        <td><%= form_for :advert, url: upload_advert_url(2), multipart: true do |f| %>
             <%= f.label "Select File" %>
             <%= f.file_field "upload" %>

              <%= submit_tag "Upload" %>
          <% end %></td>
      </tr>
      <tr>
        <td>
          <h5>Rolling Advert Banner # 3</h5>
          <%= image_tag load_advert "scrolling-advert-3", "http://placehold.it/651x85" %>
        </td>
        <td><%= form_for :advert, url: upload_advert_url(3), multipart: true do |f| %>
             <%= f.label "Select File" %>
             <%= f.file_field "upload" %>

              <%= submit_tag "Upload" %>
          <% end %></td>
      </tr>
      <tr>
        <td>
          <h5>Rolling Advert Banner # 4</h5>
          <%= image_tag load_advert "scrolling-advert-4", "http://placehold.it/651x85" %>
        </td>
        <td>
          <%= form_for :advert, url: upload_advert_url(4), multipart: true do |f| %>
             <%= f.label "Select File" %>
             <%= f.file_field "upload" %>

              <%= submit_tag "Upload" %>
          <% end %>
        </td>
      </tr>
      <tr>
        <td>
          <h5>Rolling Advert Banner # 5</h5>
          <%= image_tag load_advert "scrolling-advert-5", "http://placehold.it/651x85" %>
        </td>
        <td><%= form_for :advert, url: upload_advert_url(5), multipart: true do |f| %>
             <%= f.label "Select File" %>
             <%= f.file_field "upload" %>

              <%= submit_tag "Upload" %>
          <% end %></td> 
      </tr>
    </tbody>
</div>

app/views/admin_actions/manage_posts.html.erb
<div id="admin-actions-manage-posts" class="admin-action-pages">
<h2>Manage Posts</h2>
<p>You can remove or delete spam using this tool.</p>
<table class="table table-striped">
  <thead>
    <tr><th>ID</th><th>Title</th>
      <th style="width: 200px">Entry</th><th>User</th><th>Name</th><th>Age</th><th>Former Job</th>
      <th>Votes<br>Good# | Bad# | Spam#</th>
      <th>Queued?</th>
      <th>Action</th></tr>
  </thead>
  <tbody>
<% @posts.each do |post| %>
<tr>
  <td><%= post.id %></td>
  <td><%= link_to post.title, single_url(hash: post.permalink) %></td>
  <td><%= post.entry %></td>
  <td><%= post.user_id != nil ? post.user.email : "Admin" %></td>
  <td><%= post.name %></td>
  <td><%= post.age %></td>
  <td><%= post.former_job %></td>
  <td><%= post.total_good %> | <%= post.total_bad %> | <%= post.reported_spam %></td>
  <td>
     <%= post.post_queue != nil ? "Yes" : "No" %>
  </td>
  <td><%= link_to "Spam", manage_posts_url(post, "hide"), method: "post"  %>
      <br/>
      <% if post.user_id == nil%>
      	<%= link_to "Edit", edit_seed_url(post.id) %><br/>
      <% end %>
      <% if post.post_queue != nil %>
        <% if !post.post_queue.pushed %>
          <%= link_to "Unqueue", manage_posts_url(post, "unqueue"), method: "post" %>
        <% else %>
          Pushed
        <% end %>
      <% else %>
        <%= link_to "Queue", manage_posts_url(post, "queue"), method: "post" %>
        <%= link_to "Delete", manage_posts_url(post, "delete"), method: "delete" %><br/>        
      <% end%>
  </td>
</tr>
<% end %>
</tbody>
</table>
<%= paginate @posts %>
</div>

app/views/admin_actions/manage_queue.html.erb
<div id="admin-action-manage-queue-page" class="admin-action-pages">
  <div>
    <nav class="right-pull navbar">
      <ul class="nav">
        <li><%= link_to "Queued Items", "?pushed=false"%></li>
        <li><%= link_to "Pushed Items", "?pushed=true" %></li>
        <li><%= link_to "Consume Queue", admin_actions_consume_queue_path, method: "post" %></li>
      </ul>
    </nav>
    <div class="clear"></div>
  </div>
  <table class="table table-striped">
    <thead>
      <tr><th>Post ID</th><th style="width: 400px;">Post Entry</th><th>Entry Date</th><th>Date Queued</th><th>Action</th></tr>
    </thead>
    <tbody>
      <% @queue_items.each do |item| %>
        <tr>
          <td><%= item.post_id %></td>
          <td><p><strong>Name, Age, Former Job:</strong>
                <%= "#{item.post.name} | #{item.post.age} | #{item.post.former_job}" %></p>
              <p><%= item.post.entry %></p>
            </td>
          <td><%= item.post.created_at %></td>
          <td><%=  item.created_at %></td>
          <td>
            <% if !item.pushed %>
              <%= link_to "Unqueue", manage_posts_url(item.post, "unqueue"), method: "post" %><br />
              <%= link_to "Force Push", force_push_url(item), method: "post" %>            
            <% end %>            
          </td>
        </tr>
      <% end %>
      
    </tbody>
  </table>
  <%= paginate @queue_items %>
</div>

app/views/admin_actions/manage_spam.html.erb
<div id="admin-actions-manage-posts" class="admin-action-pages">
<h2>Manage Spam</h2>
<p>You can manage Spams using this tool</p>
<table class="table table-striped">
  <thead>
    <tr><th>ID</th><th>Title</th>
      <th style="width: 200px">Entry</th><th>User</th><th>Name</th><th>Age</th><th>Former Job</th>
        <th>Spam#</th>
        <th>Action</th></tr>
  </thead>
  <tbody>
<% @posts.each do |post| %>
<tr>
  <td><%= post.id %></td>
  <td><%= link_to post.title, single_url(hash: post.permalink) %></td>
  <td><%= post.entry %></td>
  <td>THis is the email of user <br/> for the to many part</td>
  <td><%= post.name %></td>
  <td><%= post.age %></td>
  <td><%= post.former_job %></td>
  <td><%= post.reported_spam %>
  <td><%= link_to "Show", manage_spam_url(post, "show"), method: "post" 
              %><br/>
        <%= link_to "Delete", manage_spam_url(post, "delete"), method: "delete"
            %></td>
</tr>
<% end %>
</tbody>
</table>
<%= paginate @posts %>
</div>

app/views/admin_actions/new.html.erb
<div id="admins-new">
  <h2>Add New Admin</h2>
<%#form type="POST" action="<%= edit_admin_path(@admin) " class="form-horizontal"> %>
  <%= form_for @admin, url: admin_action_path do |f| %>
      <%= render 'shared/admin_error_messages' %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>
     
      <div class="clear"></div>
      <%= f.submit "Add New Admin", class: "btn btn-large btn-primary" %>
  <% end %>
  <%#/form> %>
</div>

app/views/admin_actions/show.html.erb
<div id="admins-show">
  <h2><%= @admin.name %></h2>
<%#form type="POST" action="<%= edit_admin_path(@admin) " class="form-horizontal"> %>
  <h3><%= @admin.email%></h3>
  <div><%= link_to "Edit", edit_admin_path(@admin) %></div>
</div>

app/views/admin_actions/spam.html.erb
<h1>Admins#spam</h1>
<p>Find me in app/views/admins/spam.html.erb</p>