config/routes.rb
Resignako::Application.routes.draw do
  
  get "fb_oauth/start"

  get "fb_oauth/callback"

  
  
  match 'admin_actions/manage_spam/:id/:task' => 'admin_actions#manage_spam', as: 'manage_spam'
  match 'admin_actions/manage_posts/:id/:task' => 'admin_actions#manage_posts', as: 'manage_posts'
  
  match 'admin_actions/edit_seed/:id' => 'admin_actions#edit_seed', as: 'edit_seed', via: [:get, :put]
  match 'admin_actions/force_push/:id' => 'admin_actions#force_push', as: 'force_push', via: [:post]
  match 'admin_actions/delete_queue/:id' => 'admin_actions#delete_queue', as: 'delete_queue', via: [:delete]
  match 'admin_actions/upload_advert/:id' => 'admin_actions#upload_advert', as: 'upload_advert', via: [:post, :get]
  match 'free/:hash' => 'posts#single', :as => :single
  
  match "admin_actions"   => 'admin_actions#index'
  
  get "admin_actions/manage_adverts"
  get "admin_actions/manage_queue"
  get "admin_actions/manage_spam"
  get "admin_actions/manage_posts"  
  get "admin_actions/add_seed"
  post "admin_actions/create_seed"
  post "admin_actions/consume_queue"
  get "admin_actions/consume_queue"
  
  get "admins/login"
  resources :admins
  
  resources :admin_sessions, only: [:new, :create, :destroy]
  match '/signin', to: 'admin_sessions#new'
  match '/signout', to: 'admin_sessions#destroy', via: :delete
  
  match '/change_password', to: 'admin_sessions#change_password', via: [:get, :post]
  match '/change_pw', to: 'admin_sessions#admin_change_password', via: [:get, :put]
  
  get "contact_form/new"
  get "contact_form/create"
  get "company/about"
  get "company/contact"
  get "company/terms"

  get "users/add"
  get "users/edit"
  get "users/delete"

  get "posts/hot"
  get "posts/new"
  get "posts/submit"
  get "posts/vote_down"
  get "posts/report"
  get "posts/single"
  post "posts/create"
  get "posts/verify"
  
  match "posts/vote_up/:id", to: 'posts#vote_up', as: 'post_vote_up'
  match "posts/vote_down/:id", to: 'posts#vote_down', as: 'post_vote_down'
  match "posts/update_vote_up/:id", to: 'posts#update_vote_up', as: 'post_update_vote_up'
  match "posts/update_vote_down/:id", to: 'posts#update_vote_down', as: 'post_update_vote_down'
  match "posts/report/:id", to: 'posts#report', as: 'post_report'
  
  match 'about' => 'company#about'
  match 'terms' => 'company#terms'
  match 'topgood' => 'posts#top_good'
  match 'topbad' => 'posts#top_bad'
  match 'new' => 'posts#new'
  match 'hot' => 'posts#hot'
  match 'submit' => 'posts#submit'
  match 'contact' => 'contact_form#new'
  
  match 'feed' => 'posts#feed'
  
  match 'register' => 'users#register'
  
  get 'posts/fb_verify'
  get 'posts/callback'
  
  post "contact_form/create"
  

  
  root :to => 'posts#new'

end

app/views/layouts/_entry.html.erb
<div class="entry-item">
  <div class="entry-header-area">
    <h3 class="user-name pull-left"><%= link_to @post.title, single_url(hash: (@post.permalink)) %></h3>
    <div class="timestamp-area pull-right">
    <%= link_to @post.created_at.to_formatted_s(:long), single_url(hash: (@post.permalink)) %>
    </div>
    <div class="clear"></div>
  </div>
  <div class="user-post">
    <%= simple_format(@post.entry) %>    
  </div>
  <div class="user-source-data">
    <h4 class="user-name pull-right">- <%= @post.name %>, <%= @post.age %>, <%= @post.former_job %></h4>
    <div class="clear"></div>
  </div>
  <div class="entry-votes">
    <button class="voter-element pull-left btn up" post-id="<%= @post.id %>">
      <%
      	@postVote = PostsVote.new	
      	@postVote.unique_identifier = cookies[:unique_resignako_id]
      	@postVote.vote_good = true
      	@postVote.post_id = @post.id
      %>
      
      <%= sprite_tag (@post_votes_good && @post_votes_good.include?(@postVote)) ? "upvote-active" : "upvote-inactive" %>
      <span><strong><%= @post.total_good %></strong></span>
    </button>
    <button class="voter-element pull-left btn down" post-id="<%= @post.id %>">
      <%
      	@postVote = PostsVote.new
      	@postVote.unique_identifier = cookies[:unique_resignako_id]
      	@postVote.vote_bad = true
      	@postVote.post_id = @post.id
      %>
      <%= sprite_tag (@post_votes_bad && @post_votes_bad.include?(@postVote)) ? "downvote-active" : "downvote-inactive" %>
      <span><strong><%= @post.total_bad %></strong></span>
    </button>
    <a href="<%= single_url(hash: (@post.permalink)) %>" class="btn pull-left facebook-commentcount">
    	Comments: <fb:comments-count href="<%= single_url(hash: (@post.permalink)) %>">0</fb:comments-count>
    </a>
    <%
    %>
    <%#= link_to "0 Comments", single_url(hash: (@post.permalink)), class: "btn  livefyre-commentcount pull-left", #btn-info
    #						  :"data-lf-site-id" => 324888,
    # 						  :"data-lf-article-id" => single_url(hash: (@post.permalink)) 
    %>
    <ul class="like-buttons">
      <li class="fb-like">
      	<iframe src="//www.facebook.com/plugins/like.php?href=<%=u single_url(hash: (@post.permalink)) %>&amp;send=false&amp;layout=button_count&amp;width=50&amp;show_faces=false&amp;font&amp;colorscheme=light&amp;action=like&amp;height=21&amp;appId=488599381199316" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:90px; height:21px;" allowTransparency="true"></iframe>
      </li>
      <li class="twitter-like">
        <a href="https://twitter.com/share" class="twitter-share-button" data-url="<%= single_url(hash: (@post.permalink)) %>" data-text="<%= @post.title %>" data-via="NagresignAko" data-hashtags="nagresignako">Tweet</a>
      </li>
      <li class="g-plus-one">
        <g:plusone size="medium" href="<%= single_url(hash: (@post.permalink)) %>"></g:plusone>
      </li>
    </ul>    
    <div class="clear"></div>
    <div class="report-spam-area pull-right">
    <%
    	@postVote = PostsVote.new
      	@postVote.unique_identifier = cookies[:unique_resignako_id]
      	@postVote.set_spam = true
      	@postVote.post_id = @post.id
      	
    	if (!@post_votes_spam || !@post_votes_spam.include?(@postVote)) 
    %>
      <a href="#" post-id="<%= @post.id %>">
        <i class="icon-flag"></i>
        <span>Report as Spam</span>
      </a>
    <%
    	end
    %>	
    </div>
    <div class="clear"></div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
<%#    <a href="#">This is something not yet made</a> &copy; %>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",    about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "Terms and Service", terms_path %></li>
    </ul>
  </nav>
</footer>

<footer class="navbar scroll-to-top-area navbar-fixed-bottom">
  <div class="navbar-inner pull-right">
    <a href="javascript: void(0);" class="brand" 
    onclick="$('html, body').animate({scrollTop : 0},'slow');">
    <%= image_tag "scroll-to-top.png", class: "scroll-to-top" %></a>
  </div>
</footer>

app/views/layouts/_header.html.erb
    <header class="navbar navbar-banner navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to (image_tag "base/header.png"), root_url, id: "logo" %>

          <nav id="main-nav-area">
            <ul class="nav pull-left">
              <li class="new-nav-item">
                <%= link_to (sprite_tag is_new? ? "new-active" : "new-inactive"),   new_path, class: "hd-link-item new-path" %>
              </li>
              <li class="hot-nav-item">
                <%= link_to (sprite_tag (is_hot? || is_topgood? || is_topbad?) ? "hot-active" : "hot-inactive"),    hot_path, class: "hd-link-item hot-path" %>
              </li>
              <%# li><%= link_to "Top Good",    topgood_path, class: "hd-link-item hot-path" </li> %>
              <%# li><%= link_to "Top Bad",    topbad_path, class: "hd-link-item hot-path" </li>%>
              <li class="submit-nav-item">
                <%= link_to (sprite_tag is_submit? ? "submit-active" : "submit-inactive"), submit_path, class: "hd-link-item submit-path" %>
              </li>
            </ul>
          </nav>
          <% if is_hot? or is_topgood? or is_topbad? %>
          <nav id="hot-top-items"> 
          	<ul>
          		<li>
          			<%= link_to (sprite_tag is_topgood? ? "topgood-active" : "topgood-inactive"), topgood_path, class: "hd-link-item topgood-path" %>
          		</li>
          		<li>
          			<%= link_to (sprite_tag is_topbad? ? "topbad-active" : "topbad-inactive"), topbad_path, class: "hd-link-item topbad-path" %>
          		</li>
          	</ul>
          </nav>
          <% end %>
        </div>
      </div>
    </header>
    
    <%# This header will be invisible until user scrolls down%>
    <header class="navbar navbar-scrolled navbar-fixed-top">
      <div class="navbar-inner">
        <ul class="nav">
          <li class="<%=  "active" if action_name == "new" %>"><%= link_to "New", new_path%></li>
          <li class="<%=  "active" if action_name == "hot" %>"><%= link_to "Hot", hot_path%></li>
          <li class="pull-right <%=  "active" if action_name == "submit" %>"><%= link_to "Submit", submit_path%></li>
        </ul>  
      </div>
    </header>

app/views/layouts/_sidebar.html.erb
<%# For facebook logs%>
<div id="sidebar-advert">
  <%#= link_to (image_tag load_advert "sidebar-right", "http://placehold.it/300x300"), "http://www.freelancer.com" %>
  <%= image_tag load_advert "sidebar-right", "http://placehold.it/300x300" %>
</div>

<div id='facebook-sidebar-area'>
  <fb:like-box href="https://www.facebook.com/pages/Nagresignako/336926053091417" width="292" show_faces="true" stream="false" header="true"></fb:like-box>
</div>

<%# For twitter logs%>
<div id="twitter-sidebar-area">
<a class="twitter-timeline" href="https://twitter.com/search?q=%23nagresignako" data-widget-id="297985860975075328">Tweets about "#nagresignako"</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
</div>

<%= render 'layouts/footer'%>

app/views/layouts/admin_base.html.erb
<!DOCTYPE html>
<html xmlns:fb="http://ogp.me/ns/fb#">
<head>
  <title>Resignako</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body id="admin-base" data-controller="<%= controller_name %>" data-action="<%= action_name %>">
<div id="page-container">  
  <div class="container-fluid">
    <div class="row">
      <div class="span12">
        <h1>Nagresignako.com Admin Pages</h1>
      </div>
    </div>
    <div class="row">
    	<div class="span12">
	    	<ul class="nav nav-tabs">
	          <li><%= link_to "View Admins", admins_path %></li>
	          <li><%= link_to "Add Admins", new_admin_path %></li>
	          <li><%= link_to "Add Seed Content", admin_actions_add_seed_path %></li>
	          <li><%= link_to "Manage Posts", admin_actions_manage_posts_path %>
	          <li><%= link_to "Manage Spammers", admin_actions_manage_spam_path %></li>
	          <li><%= link_to "Social Push Queue", admin_actions_manage_queue_path %></li>
	          <li><%= link_to "Advert Management", admin_actions_manage_adverts_path %></li>
	          <li><%= link_to "Logout", signout_path, method: "delete" %></li>
	        </ul>
    	</div>
    </div>
    <div class="row-fluid">
      <div class="span12">
        <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
        <!-- This area is for the sidebar-->
      </div>
    </div>
  </div>
</div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns:fb="http://ogp.me/ns/fb#">
<head>
  <title>NagResignAko<%= content_for?(:page_title) ? (" | " + yield(:page_title) ) : "" %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <%# Open Graph Metas %>
    
  <meta property="og:image" content="http://<%= request.host_with_port %>/assets/boy.png"/>
  <meta property="og:title" content="<%= content_for?(:page_title) ? (yield(:page_title) ) : "" %>"/>
  <meta property="og:description" content="<%= content_for?(:page_description) ? (yield(:page_description) ) : "So you think your ex-job is the worst? Let everyone decide on that. It's your time to rant!" %>" />
  <meta property="og:type" content="website" />
  
  <% if content_for?(:page_url) %>
    <meta property="og:url" content="<%=  yield(:page_url)  %>" />
  <% end %>

  
  <% #ICON %>
  <link rel="shortcut icon" type="image/x-icon" href="/assets/boy.png">
  <%# Livefyre
   %>
  <script type="text/javascript" src="http://zor.livefyre.com/wjs/v1.0/javascripts/CommentCount.js"></script>
</head>
<body data-controller="<%= controller_name %>" data-action="<%= action_name %>">
<%= render 'layouts/header'%>
<div id="page-container">  
  <div class="container-fluid">
    <div class="row-fluid">
      <div class="span8">
        <%= yield %>
      </div>
      <div class="span4">
        <%= render 'layouts/sidebar' %>
        <!-- This area is for the sidebar-->
      </div>
    </div>
  </div>
</div>

</body>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=476134752451078";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

<script type="text/javascript" src="https://apis.google.com/js/plusone.js"></script>

<script type="text/javascript">
	LF.CommentCount({
	    replacer: function(element, count) {
	        element.innerHTML = count +' Comment'+ (count === 1 ? '' : 's');
	    }
	});
</script>
<% #Google Analytics %>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-39614794-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</html>

app/views/layouts/blank_base.html.erb
<!DOCTYPE html>
<html xmlns:fb="http://ogp.me/ns/fb#">
<head>
  <title>Resignako</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body data-controller="<%= controller_name %>" data-action="<%= action_name %>">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
  <%= yield %>
</body>
</html>